#!/bin/bash

VERSION=1.0.1

if ! test -f "$HOME/.gitconfig"; then
  touch $HOME/.gitconfig
fi

docker container run -it --rm \
  -v $(pwd):/app \
  -v $HOME/.gitconfig:/home/user/.gitconfig:ro \
  -u $(id -u ${USER}):$(id -g ${USER}) \
  -e HOME=/home/user \
  presidenten/lazygit:$VERSION
